{% set name = "pycairo" %}
{% set version = "1.18.1" %}
{% set sha256 = "70172e58b6bad7572a3518c26729b074acdde15e6fee6cbab6d3528ad552b786" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pygobject/pycairo/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - windows.patch  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - m2w64-toolchain  # [win]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - pkg-config                         # [not win]
    - m2w64-pkg-config                   # [win]
  host:
    - m2w64-pkg-config                   # [win]
    - cairo
    - pthread-stubs
    - python
  run:
    - cairo
    - python

test:
  imports:
    - cairo

about:
  home: http://cairographics.org/pycairo/
  license: LGPL 2.1, MPL 1.1
  license_file: COPYING
  summary: 'Python bindings for the Cairo graphics library.'
  dev_url: https://github.com/pygobject/pycairo/

extra:
  recipe-maintainers:
    - pkgw
