{% set name = "pycairo" %}
{% set version = "1.20.0" %}
{% set sha256 = "5695a10cb7f9ae0d01f665b56602a845b0a8cb17e2123bfece10c2e58552468c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pygobject/pycairo/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - windows.patch  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [py < 35]

requirements:
  build:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - m2w64-toolchain  # [win]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - m2w64-pkg-config                   # [win]
  host:
    - m2w64-pkg-config  # [win]
    - cairo
    - cython
    - pip
    - pthread-stubs
    - python
  run:
    - cairo
    - python

test:
  imports:
    - cairo

about:
  home: http://cairographics.org/pycairo/
  license: LGPL 2.1, MPL 1.1
  license_file: COPYING
  summary: 'Python bindings for the Cairo graphics library.'
  dev_url: https://github.com/pygobject/pycairo/

extra:
  recipe-maintainers:
    - pkgw
