travis:
  secure:
    BINSTAR_TOKEN: EciVgwa4RkXq1P3N8ivV2gLZgXb7ENShD8ZxH6vzDSrDub2ejGCVgiDTuAot3S7eZGXslgcPtsnZSAjRk21+ua0SvvZuQejgIU46k3i2nbT/cvsrWF7ieojMpfuMOpiOMq5HSOJgK1FZg1bsie2XmZ4L7fMvN20meY5jLONibQmJg7yJfS9OnyHei1a+IumrpbrEimWwVY4TcvuisLITNmLXZLpFLSoWDO6P2OI6ve2NhKfhjmlAUHkdM0NlXeV+wUOOdSJ1b21Gc96zf8B/h0uxv8UOwqDa/vNykqTbXcnHCe1iSwD6I3PIban6fZ9DhONWtyLFpZX5tZO8cwJGAC9CiKYJMdNoMDIZnDfZNxsC6KHJN4CFgP+zaunfQQ/Ctm8pi/+7438/v2ALgi+u11dZA1+UeU5Haba1EXbzcKTqAYL2fZoVJ/tZeWAcKih+3EGjTfln318xxRrRbiRkcuRyASGST6HBl/Xf7DBzYM1FhGUKVg9PUWMslCMacypVZ+35MR2Xydii0GchDHhE2WmGWmhS0lCp6zPRCa57OkGUn0U5+sNdv1nUH3RwFGfU1M+La0zO/K8FD63mrJIQkRwuqWdec/vsEnH5/ZMmEwW1EdOq7h9VLXa6DRluIJSK2DmuiuzFbrBXGTwutEgfGflrqLiSPE38DTpfB2Fr0SI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
