travis:
  secure:
    BINSTAR_TOKEN: o9aC63cSjxZcmoM934KE37qWevdfaWyomYoJeki/7m0bpyGH9QAC53pl7VxfVfLVJBJrpcP+LsCLmalCl9W7I98QcAj/8nESXbQBruyq2mwDyVQso/rjK+9ejO52Dpkct3LCUs0t2O7C8h1/J8eGL0FvDhibPmoPfplomktuMtLVkWEqNU0VSzcW2Y/4zrNwHgiazmXR11CQy9BQ6A5edzitoGK5Q7rkP9mEu12ZMJ/J+YyRoFeC6kZ6NnaoPi+qtNk1DLdTyoQWZHSpM6tIphH7kaEiuH+wS7V9p/1flEkbUi09YeXJ0YxEwUBRtGCZS/VKE3iXCDQxiZ1t3hg9U7+4VShlDkRYBTfQ+rOKP7pj64zqcGUD1k/R9MHKpgt//3NrPDPRCtn2sgO91d+hO1UN/pvj4XgyJLoEuAyWMi15F69NDKyVByV5iMM/5xj76QC2u4cUHAGAaCtKcQTAUhugoGS3vKXV1lWJ0UJZASusiedLAwK8VIAOAJwt43AptEbfilogSmtIytWrBV1iaBkFx8I38cvFBvnaxsnqoQoPzyXmo3sPv/oa5ooU7A0MiNvZQAogeE/Oq5WUkY+amS+U5e7ZNxha7CVNpCzzIyk8pzPhXhyS9mXijs46BRUVpBKSwnuZiux93S5jLXXpP5plUinhEPx3HZ3CSnN2pnQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
